# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6789a880302943852085ce87f1e1b0da134dfcd33a285481ab228fe67edb0ca3aa51d7cbab7ea33e9de4b174b71900d28969d0f739b3be07a39c811e6570c33d

test:
  secret_key_base: 8008d3324d3c831acbeb1ca5a9ac98ad057114282930cc76060ccc0e2eb029f8f98895ef2e037757c3ed9676024a80574c7d24a3cbbcf610ff9fd3edb3370a9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
